version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: kanban-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kanban_user']
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://kanban_user:kanban_password@postgres:5432/kanban_board?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-change-this-in-production}
      SOCKET_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kanban-network
    command: sh -c "npx prisma migrate deploy && node server.js"

volumes:
  postgres_data:

networks:
  kanban-network:
    driver: bridge


